### ISSUE TITLE
Feature move'n'fight

### ISSUE THREAD

**Issue by WeirdEraCont** [FromageChaud/gss#10]
@FromageChaud Problème lors de la compilation non identifié lors du dernier commit (01/10/17) de la branche move'n'fight. Help needed :( cf commentaire dans le script _scr_zombie_fight_

**Comment by FromageChaud** [comment]
I'm on it, je te tiens au courant dans les qques min

**Comment by FromageChaud** [comment]
@WeirdEraCont  Wouah c'est fou comme c'est bien Github, j'ai reçu un mail pour la notif du coup j'ai tout de suite regardé ^^ 
Je comprends le problème ... Ca m'a pris du temps mais en fait c'était simple
(au passage je me suis trompé sur les objets et "with" https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/401_05_addressing.html )

**Comment by WeirdEraCont** [comment]
Bordel, j'avais oublié les break...
